"""Initial migration - all models

Revision ID: 8960f76fde21
Revises: 
Create Date: 2026-02-17 18:43:32.898926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8960f76fde21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('group_payment_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_payment_id'], ['group_payment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_payment_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_fee_structure_id'), ['fee_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_group_payment_id'), ['group_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_fee_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('fee_structure_classes',
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('class_grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_grade_id'], ['class_grade.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ),
    sa.PrimaryKeyConstraint('fee_structure_id', 'class_grade_id')
    )
    op.create_table('payment_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('group_payment_id', sa.Integer(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_payment_id'], ['group_payment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['fee_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_payment_id'),
    sa.UniqueConstraint('payment_id')
    )
    with op.batch_alter_table('payment_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_receipt_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_receipt_receipt_number'))

    op.drop_table('payment_receipt')
    op.drop_table('fee_structure_classes')
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_payment_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_status'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_payment_date'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_group_payment_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_fee_structure_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_due_date'))

    op.drop_table('fee_payment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
