"""Change gender field to String(10) for student model

Revision ID: 8963baa45b8e
Revises: 8960f76fde21
Create Date: 2026-02-18 12:48:09.039925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8963baa45b8e'
down_revision = '8960f76fde21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
