"""
Student Management Routes

This blueprint handles all student-related routes:
- List students
- Add student
- Edit student
- View student details
- Delete/deactivate student
- Search and filter
- Export to Excel
"""

from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, send_file, current_app
from flask_login import login_required, current_user
from flask_babel import gettext as _
from app import db
from app.models import Student, ClassGrade, Family, FeePayment
from app.forms import StudentForm, StudentEditForm
from sqlalchemy import or_
from datetime import date
import io
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

bp = Blueprint('students', __name__, url_prefix='/students')


@bp.route('/')
@login_required
def list_students():
    """
    List all students with pagination, search, and filter
    
    URL: /students/
    """
    # Get query parameters
    page = request.args.get('page', 1, type=int)
    search = request.args.get('search', '', type=str)
    class_filter = request.args.get('class', 0, type=int)
    status_filter = request.args.get('status', 'all', type=str)
    
    # Start with base query
    query = Student.query
    
    # Apply search filter
    if search:
        # Search in name, student_id, admission_number
        search_pattern = f'%{search}%'
        query = query.filter(
            or_(
                Student.first_name.like(search_pattern),
                Student.last_name.like(search_pattern),
                Student.student_id.like(search_pattern),
                Student.admission_number.like(search_pattern),
                Student.father_name.like(search_pattern)
            )
        )
    
    # Apply class filter
    if class_filter > 0:
        query = query.filter_by(class_grade_id=class_filter)
    
    # Apply status filter
    if status_filter == 'active':
        query = query.filter_by(is_active=True)
    elif status_filter == 'inactive':
        query = query.filter_by(is_active=False)
    
    # Order by student_id (newest first)
    query = query.order_by(Student.student_id.desc())
    
    # Paginate results (50 per page)
    pagination = query.paginate(
        page=page,
        per_page=50,
        error_out=False
    )
    
    students = pagination.items
    
    # Get all classes for filter dropdown
    classes = ClassGrade.query.filter_by(is_active=True).order_by(ClassGrade.order).all()
    
    # current_language is automatically injected by context processor
    return render_template(
        'students/list.html',
        students=students,
        pagination=pagination,
        classes=classes,
        search=search,
        class_filter=class_filter,
        status_filter=status_filter,
        title=_('Students')
    )


@bp.route('/add', methods=['GET', 'POST'])
@login_required
def add_student():
    """
    Add a new student
    
    URL: /students/add
    GET: Show add student form
    POST: Process form and create student
    """
    form = StudentForm()
    
    # Populate class dropdown
    form.class_grade_id.choices = [(0, _('-- Select Class --'))] + [
        (c.id, c.class_name) for c in ClassGrade.query.filter_by(is_active=True).order_by(ClassGrade.order).all()
    ]
    
    # Populate family dropdown
    form.family_id.choices = [(0, _('-- Select Family --'))] + [
        (f.id, f"{f.family_code} - {f.father_name}") 
        for f in Family.query.order_by(Family.family_code).all()
    ]
    
    # current_language is automatically injected by context processor
    if form.validate_on_submit():
        try:
            # Create new student
            student = Student(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                father_name=form.father_name.data,
                date_of_birth=form.date_of_birth.data,
                gender=form.gender.data,
                class_grade_id=form.class_grade_id.data if form.class_grade_id.data else None,
                admission_date=form.admission_date.data,
                # admission_number will be auto-generated by event listener
                address=form.address.data or None,
                parent_guardian_name=form.parent_guardian_name.data,
                parent_primary_contact=form.parent_primary_contact.data,
                parent_secondary_contact=form.parent_secondary_contact.data or None,
                family_id=form.family_id.data if form.has_siblings.data == 'yes' and form.family_id.data else None,
                is_active=form.is_active.data
            )
            
            # Student ID and admission_number will be auto-generated by event listener
            
            db.session.add(student)
            db.session.commit()
            
            flash(_('Student added successfully! Student ID: %(id)s', id=student.student_id), 'success')
            return redirect(url_for('students.view_student', id=student.id))
            
        except Exception as e:
            db.session.rollback()
            flash(_('Error adding student: %(error)s', error=str(e)), 'error')
            current_app.logger.error(f"Error adding student: {e}")
    
    # current_language is automatically injected by context processor
    return render_template('students/add.html', form=form, title=_('Add Student'))


@bp.route('/<int:id>')
@login_required
def view_student(id):
    """
    View student details
    
    URL: /students/<id>
    Shows complete student information, payment history, etc.
    """
    student = Student.query.get_or_404(id)
    
    # Get student's payment history
    payments = FeePayment.query.filter_by(student_id=student.id).order_by(FeePayment.payment_date.desc()).limit(10).all()
    
    # Get pending fees
    pending_payments = FeePayment.query.filter(
        FeePayment.student_id == student.id,
        FeePayment.status.in_(['PENDING', 'OVERDUE', 'PARTIAL'])
    ).all()
    
    # Calculate total pending
    total_pending = sum(float(p.amount) for p in pending_payments)
    
    # Get family members (siblings) if student has family
    siblings = []
    if student.family:
        siblings = Student.query.filter(
            Student.family_id == student.family_id,
            Student.id != student.id
        ).all()
    
    return render_template(
        'students/view.html',
        student=student,
        payments=payments,
        pending_payments=pending_payments,
        total_pending=total_pending,
        siblings=siblings,
        title=_('Student Details')
    )


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_student(id):
    """
    Edit student information
    
    URL: /students/<id>/edit
    GET: Show edit form with current data
    POST: Update student information
    """
    student = Student.query.get_or_404(id)
    form = StudentEditForm(obj=student, student=student)
    
    # Populate dropdowns
    form.class_grade_id.choices = [(0, _('-- Select Class --'))] + [
        (c.id, c.class_name) for c in ClassGrade.query.filter_by(is_active=True).order_by(ClassGrade.order).all()
    ]
    
    form.family_id.choices = [(0, _('-- No Family --'))] + [
        (f.id, f"{f.family_code} - {f.father_name}") 
        for f in Family.query.order_by(Family.family_code).all()
    ]
    
    if form.validate_on_submit():
        try:
            # Update student fields
            student.first_name = form.first_name.data
            student.last_name = form.last_name.data
            student.father_name = form.father_name.data
            student.date_of_birth = form.date_of_birth.data
            student.gender = form.gender.data
            student.class_grade_id = form.class_grade_id.data if form.class_grade_id.data else None
            student.admission_date = form.admission_date.data
            # admission_number is auto-generated, don't update it
            student.address = form.address.data or None
            student.parent_guardian_name = form.parent_guardian_name.data
            student.parent_primary_contact = form.parent_primary_contact.data
            student.parent_secondary_contact = form.parent_secondary_contact.data or None
            student.family_id = form.family_id.data if form.has_siblings.data == 'yes' and form.family_id.data else None
            student.is_active = form.is_active.data
            
            db.session.commit()
            
            flash(_('Student updated successfully!'), 'success')
            return redirect(url_for('students.view_student', id=student.id))
            
        except Exception as e:
            db.session.rollback()
            flash(_('Error updating student: %(error)s', error=str(e)), 'error')
            current_app.logger.error(f"Error updating student: {e}")
    
    return render_template('students/edit.html', form=form, student=student, title=_('Edit Student'))


@bp.route('/<int:id>/delete', methods=['POST'])
@login_required
def delete_student(id):
    """
    Delete or deactivate student
    
    URL: /students/<id>/delete
    POST: Deactivate student (soft delete)
    """
    student = Student.query.get_or_404(id)
    
    try:
        # Soft delete: Set is_active to False
        # This preserves data but hides student from active lists
        student.is_active = False
        db.session.commit()
        
        flash(_('Student deactivated successfully.'), 'success')
    except Exception as e:
        db.session.rollback()
        flash(_('Error deactivating student: %(error)s', error=str(e)), 'error')
    
    return redirect(url_for('students.list_students'))


@bp.route('/export')
@login_required
def export_students():
    """
    Export students to Excel
    
    URL: /students/export
    Generates Excel file with all student data
    """
    # Get filter parameters (same as list)
    search = request.args.get('search', '', type=str)
    class_filter = request.args.get('class', 0, type=int)
    status_filter = request.args.get('status', 'all', type=str)
    
    # Build query (same as list_students)
    query = Student.query
    
    if search:
        search_pattern = f'%{search}%'
        query = query.filter(
            or_(
                Student.first_name.like(search_pattern),
                Student.last_name.like(search_pattern),
                Student.student_id.like(search_pattern),
                Student.admission_number.like(search_pattern)
            )
        )
    
    if class_filter > 0:
        query = query.filter_by(class_grade_id=class_filter)
    
    if status_filter == 'active':
        query = query.filter_by(is_active=True)
    elif status_filter == 'inactive':
        query = query.filter_by(is_active=False)
    
    students = query.order_by(Student.student_id).all()
    
    # Create Excel workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Students"
    
    # Add headers
    headers = [
        _('Student ID'), _('First Name'), _('Last Name'), _('Father Name'),
        _('Date of Birth'), _('Gender'), _('Class'), _('Admission Date'),
        _('Admission Number'), _('Contact'), _('Address'), _('Parent Name'),
        _('Parent Contact'), _('Family Code'), _('Status')
    ]
    ws.append(headers)
    
    # Style headers
    header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center')
    
    # Add data
    for student in students:
        ws.append([
            student.student_id,
            student.first_name,
            student.last_name,
            student.father_name,
            student.date_of_birth.strftime('%Y-%m-%d') if student.date_of_birth else '',
            student.gender,
            student.class_grade.class_name if student.class_grade else '',
            student.admission_date.strftime('%Y-%m-%d') if student.admission_date else '',
            student.admission_number,
            student.contact_number or '',
            student.address or '',
            student.parent_guardian_name,
            student.parent_contact,
            student.family.family_code if student.family else '',
            _('Active') if student.is_active else _('Inactive')
        ])
    
    # Auto-adjust column widths
    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = min(max_length + 2, 50)
        ws.column_dimensions[column_letter].width = adjusted_width
    
    # Save to memory
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    
    # Generate filename
    from datetime import datetime
    filename = f"students_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    
    return send_file(
        output,
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        as_attachment=True,
        download_name=filename
    )
